---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by westboy.
--- DateTime: 2021/3/31 4:40 下午
---

pcall(function(i)
    print(i)
end, 33)

pcall(function(i)
    print(i)
    error('error..')
end, 33)

print("---------------------")

function myfunction (n)
    n = n / nil
end

function myerrorhandler(err)
    print("ERROR:", err)
end

--status = myfunction(1)
--print(status)

status = xpcall(myfunction, myerrorhandler, 1)
print(status)