---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by westboy.
--- DateTime: 2021/3/31 4:36 下午
---


mytable = {}                          -- 普通表
mymetatable = {}                      -- 元表
setmetatable(mytable, mymetatable)     -- 把 mymetatable 设为 mytable 的元表

-- 以上代码也可以直接写成一行 mytable = setmetatable({},{})

getmetatable(mytable)

other = { foo = 3 }

t = setmetatable({}, { __index = other })

print(t.foo)