---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by westboy.
--- DateTime: 2021/3/31 3:26 下午
---

-- 泛型 for 循环，类似 Java 中的 foreach
-- ipairs 是 Lua 提供的一个迭代器函数，用来迭代数组
days = { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }
for i, v in ipairs(days) do
    print("i=" .. i .. "\t k=" .. v)
end

-- Lua repeat...until 循环
a = 10
repeat
    print("a的值为:", a)
    a = a + 1
until (a > 15)


--[  定义变量  --]
a = 10
--[  while  循环  --]
while (a < 20) do
    print("a 的值为:", a)
    a = a + 1
    if (a > 15) then
        break
    end
end


