---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by westboy.
--- DateTime: 2021/3/31 4:10 下午
---

array = { "Lua", "Tutorial" }

for key, value in ipairs(array)
do
    print(key, value)
end

print("----------无状态的迭代器----------")

function square(iteratorMaxCount, currentNumber)
    if currentNumber < iteratorMaxCount
    then
        currentNumber = currentNumber + 1
        return currentNumber, currentNumber * currentNumber
    end
end

for i, n in square, 3, 0
do
    print(i, n)
end


print("----------多状态的迭代器----------")

array = { "Lua", "Tutorial" }

function elementIterator (collection)
    local index = 0
    local count = #collection
    -- 闭包函数
    return function()
        index = index + 1
        if index <= count
        then
            --  返回迭代器的当前元素
            return collection[index]
        end
    end
end

for element in elementIterator(array)
do
    print(element)
end